controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

head_controller:
  ros__parameters:
    joints:
      - HeadYaw
      - HeadPitch
    command_interfaces:
      - position
    state_interfaces:
      - position

arm_controller:
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
    command_interfaces:
      - position
    state_interfaces:
      - position